### ISSUE TITLE
Color opacity not exported correctly

### ISSUE THREAD

**Issue by aried3r** [tudou527/marketch#100]
We experienced this recently, in the original the font has 70% opacity, in the exported HTML it's 69%.

Sketch 70%:
![email](https://cloud.githubusercontent.com/assets/1301152/15390733/b5336ada-1dbd-11e6-9d00-f623bb9a13f2.png)

Marketch 69%:
![screen shot 2016-05-19 at 14 06 36](https://cloud.githubusercontent.com/assets/1301152/15393081/8e8151b4-1dcb-11e6-8d4e-05c3b871e766.png)

**Comment by tudou527** [comment]
i think this is a bug of sketch:

![image](https://cloud.githubusercontent.com/assets/1134658/15984113/cb955928-2ff1-11e6-93c3-d96f364d5521.png)

![image](https://cloud.githubusercontent.com/assets/1134658/15984116/d9ba86cc-2ff1-11e6-8e88-71e29dbba537.png)

then you get the error css attribute as this:

```
/* Type something: */
opacity: 0.69;
font-family: AndaleMono;
font-size: 48px;
color: #210808;
```
