### ISSUE TITLE
建议加入对Symbol的支持

### ISSUE THREAD

**Issue by iparanoid** [tudou527/marketch#101]
目前的版本还不支持对Smybol内的元素进行标注
期待加入这个功能
谢谢

**Comment by jingfeng0510** [comment]
现在选择导出选中的画板时，symbol页面没有被导出，建议同时把symbol页面也导出

**Comment by poorfish** [comment]
目前的版本，界面中如果包含symbol，导出后在网页中无法选中symbol，急待解决，谢谢

**Comment by yoavchen** [comment]
HI,
Any update on when will it be possible to export symbols in selected artboards?

**Comment by tudou527** [comment]
试试 1.0.21

**Comment by iparanoid** [comment]
感谢作者的反馈 已解决
