### ISSUE TITLE
可以将字体样式名称，加入字体的代码里吗？谢谢！

### ISSUE THREAD

**Issue by hf6666** [tudou527/marketch#102]
谢谢你们制作的非常非常便利的插件！
能否将这个sketch当中的字体的样式名称也加入到代码当中呢？
<img width="238" alt="screen shot 2016-06-01 at 19 27 16" src="https://cloud.githubusercontent.com/assets/19318365/15706583/5236f56a-282f-11e6-9b3d-81590c1d9387.png">
谢谢！

**Comment by tudou527** [comment]
你指的是这个吗？
![image](https://cloud.githubusercontent.com/assets/1134658/15983980/5316e4f8-2fec-11e6-9b29-ce6ecf0ceabd.png)

**Comment by hf6666** [comment]
啊啊啊！！！就是这个！！！谢谢！！！

**Comment by tudou527** [comment]
这个功能现在就是有的
