### ISSUE TITLE
Marketch export symbols page option

### ISSUE THREAD

**Issue by pixelize** [tudou527/marketch#104]
Hi there,

First of all, thanks for the wonderful works on Marketch.
Is there any way to create an export without the symbol page ? We don't need it in our current exports :)
A checkbox in the export panel would great. What do you think ?

![](http://img15.hostingpics.net/pics/635306marketchsymbols.png)

**Comment by tudou527** [comment]
you can add "-" prefix to prevent any layer be export.  like this:

![image](https://cloud.githubusercontent.com/assets/1134658/16082580/82303b30-3344-11e6-82ae-fb061b4171c9.png)

**Comment by pixelize** [comment]
Good to know thanks for the tip @tudou527 ;)
