### ISSUE TITLE
Export SVG

### ISSUE THREAD

**Issue by kevinSuttle** [tudou527/marketch#107]
Is this possible? All I see under export options are PNG.

**Comment by tudou527** [comment]
u can add "svg" prefix for layer name to tell marketch export the layer as svg file.

**Comment by jordanwsmith** [comment]
@tudou527 could you clarify on how to correctly add a prefix in Sketch? I've tried adding ".svg" to the layer name in Sketch and exporting to Marketch, but SVG is still not appearing as an option.

**Comment by jmaferreira** [comment]
I can't export it in SVG either... How do we do it?
