### ISSUE TITLE
Export ZIP unsuccessful with Marketch

### ISSUE THREAD

**Issue by shuaffy** [tudou527/marketch#115]
I have Sketch v39.1 and tried using the latest Marketch to export a file to ZIP, but the ZIP file never shows up in the folder. Please help.

**Comment by fishsean** [comment]
更新了Sketch之后最后悔的就是Export ZIP再也用不了了，还希望作者们赶紧修复啊。
暂时用Measure的导出功能代替了Marketch，但是还是希望Marketch能更新，导出和提升效率真的是很给力了

**Comment by JohnWong** [comment]
40.3版本，导出后没有文件
