### ISSUE TITLE
Problem with opening index.html file

### ISSUE THREAD

**Issue by giang491** [tudou527/marketch#120]
After export my project from Sketch via Marketch Plug-in, I open index.html file, it only appears blank page, but other computer appears correctly, please help me! Thank you a lot.
![img_3943](https://cloud.githubusercontent.com/assets/22535501/18979537/0eb21178-86f6-11e6-9bc8-0c87ff22e5cd.JPG)
![img_3944](https://cloud.githubusercontent.com/assets/22535501/18979538/0f04a1b8-86f6-11e6-880f-c1d2711a9d1a.JPG)

**Comment by MForever78** [comment]
Hi, @giang491. What's your OS version and Safari version?

It seems to me that you're using an old version of macOS and Safari. And that explains why other computers appears correctly. Please try to upgrade your macOS and Safari. Or you may try downloading the latest Google Chrome or Firefox.

**Comment by giang491** [comment]
Thanks Tong Xingang !
My problem have been solved due to your advice.



  Best regards,


*    Giang Tran          Design *

*F5 TECH LLC *

P.O BOX 14770 Fremont, CA 94539

www.f5chat.com <http://www.wearnes.com/>    Email: giangtran@f5chat.com

*This email, including any attachment, is confidential and may also be
privileged. *
*If you have received it in error, please notify us immediately by reply
email and then delete this message from your system. *
*Please do not copy it or use it for any purpose, or disclose its contents
or any attachment to any other person. Thank you.*






2016-09-30 12:00 GMT+07:00 Tong Xingang <notifications@github.com>:

**Comment by mrengy** [comment]
I am also getting a blank screen when opening the index.html file when trying to open it locally. 

I got the following[ errors in the Chrome console](http://screencast.com/t/hwlCG9zQLnO):

- Uncaught SyntaxError: Invalid or unexpected token (data.js:1)
- Uncaught ReferenceError: pageData is not defined
    at HTMLScriptElement.xdata.onload (file:///Users/mikeeng/Desktop/cornerwise/Cornerwise_Somerville%20031516/index.html:1321:17)

Mac OS 10.11.3 / Chrome Version 54.0.2840.71 (64-bit) 

It would be non-trivial for me to update Mac OS for this.

Any help is appreciated.
