### ISSUE TITLE
plugin broken in sketch 41

### ISSUE THREAD

**Issue by martoony** [tudou527/marketch#123]
does not export anything

**Comment by Samgoldman123** [comment]
Same issue here. Sketch update causing the glitch.

**Comment by pixelula** [comment]
Yes, same here as well, does not export anything. :(

**Comment by anasandia** [comment]
any new? i really need to export my work....

**Comment by pixelize** [comment]
Same but with 4.1 but work with 4.0.3 ;)

In the meanwhile you can still download this working version here : 
http://sketchapp.com/download/sketch-40.3.zip

**Comment by canisminor1990** [comment]
### Fixed

Sketch change some method names in version 41:

<http://developer.sketchapp.com/reference/class/MSRect/>

<http://developer.sketchapp.com/reference/class/MSLayer/>

---

I have fixed them and the plugin already works in sketch 41:

<https://github.com/tudou527/marketch/pull/127>

---

Or you can try this temporarily:

<https://github.com/canisminor1990/marketch>

**Comment by pixelize** [comment]
@canisminor1990 wonderful, thanks for fixing that bug so fast ;) keep up the good work !
