### ISSUE TITLE
didn't export anything after the "exporting" loading bar

### ISSUE THREAD

**Issue by joychen0103** [tudou527/marketch#125]
i tried multiple times to try to export selected artboards as zipfile. I saw the "exporting" popup, but it just jumped to the "symbols" page, and nothings showed up in my designated folder. Please fix this~ Thanks!!

**Comment by perteraul** [comment]
This happens because Marketch doesn't work with the latest version of Sketch — v41. What I recommend you to do is to download the v40.3 from the link below and only use it to export your assets with Marketch. 

http://sketchapp.com/download/sketch-40.3.zip

**Comment by giang491** [comment]
I have the same issue and due to perteraul help my problem has been solved, thank you perteraul!
