### ISSUE TITLE
升级到sketch 4.1版本后，marketch不能工作

### ISSUE THREAD

**Issue by thing360** [tudou527/marketch#126]
升级到sketch 4.1版本后，marketch不能工作了，选择了画板之后然后选择导出，结果没有任何文件导出

**Comment by Bryan0220** [comment]
I have the same problem. How to fix it?

**Comment by rodnem** [comment]
Help !!!!
Marketch doesn't export anything under sketch4.1.
I can help in beta testing...

**Comment by canisminor1990** [comment]
### Fixed

Sketch change some method names in version 41:

<http://developer.sketchapp.com/reference/class/MSRect/>

<http://developer.sketchapp.com/reference/class/MSLayer/>

---

I have fixed them and the plugin already works in sketch 41:

<https://github.com/tudou527/marketch/pull/127>

---

Or you can try this temporarily:

<https://github.com/canisminor1990/marketch>

**Comment by zhongerxin** [comment]
Great 3Q @canisminor1990

**Comment by rodnem** [comment]
Thanks 👏

**Comment by thing360** [comment]
Thanks👍

**Comment by longalong** [comment]
45.2  整个page导出到桌面，无法生成压缩文件，单独有的artbord可以导出，有些不可以
