### ISSUE TITLE
Don't Export with Sketch Version 41.2

### ISSUE THREAD

**Issue by hieunh** [tudou527/marketch#129]
Today, I can't use Marketch export with Sketch Version 41.2, plugin loading "Exporting..." but not complete.

**Comment by pixelize** [comment]
Hey @hieunh, works perfectly good on my Sketch Version 41.2 (35397). Don't forget to update Marketch et restart Sketch

**Comment by DasBlatz** [comment]
same for me 41.2 (35397) doesn’t export the zip file

**Comment by DasBlatz** [comment]
seemed to be fixed in v1.0.22 
can somebody confirm this with 41.2 (35397)?

**Comment by MForever78** [comment]
The issue should already been fixed for a while. Closing old thread...
