### ISSUE TITLE
Marketch does not generate zip file

### ISSUE THREAD

**Issue by daria-tanygina** [tudou527/marketch#145]
Today I tried to make a Zip archive of my artwork, but nothing appeared in the chosen folder. It just writes "Exporting..." on the Page screen, then shows me the Symbol library, and nothing happens! 

Sketch version - 45,
Marketch version - 1.0.22

**Comment by anasandia** [comment]
I'm having the same issue... :S

**Comment by cynthia-ryu** [comment]
same problem...help

**Comment by daria-tanygina** [comment]
Hi,
While they're fixing the problem (I want to believe they do), I use Sketch
Measurer plugin instead. Maybe it will be helpful to you)

**Comment by MForever78** [comment]
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.
