### ISSUE TITLE
可否支持一下45版本？

### ISSUE THREAD

**Issue by AbnerChen028** [tudou527/marketch#148]
# 在45版本中无法导出

能否支持下？这个东西不能用之后工作量增加了不少额  已经离不开这个插件了

**Comment by xixigeek** [comment]
支持啊

**Comment by AbnerChen028** [comment]
无法导出，难道是因为sketch是pj版的原因？

**Comment by siroiyaksa** [comment]
同样遇到了导出问题，无法生存=成zip。
sketch版本45.1

**Comment by AbnerChen028** [comment]
` Util.cocoaScript `文件，425行所在判断直接删除，重启一下`Sketch`就好了    详情可以查看(issees149)[https://github.com/tudou527/marketch/issues/149]
