### ISSUE TITLE
export individual art boards 

### ISSUE THREAD

**Issue by da1nonly** [tudou527/marketch#15]
first off great tool, also can you add the ability to export individual art boards and have better file names for the assets like cta_button.png

**Comment by kakavvb** [comment]
soon

**Comment by tudou527** [comment]
### "export individual art boards"
i fixed this in new version(0.0.4). please reinstall form sketch tools or download zip 

### "better file names for the assets"
when you download from website, i use html5 download attribute to rename the assets. maybe it's not work correctly
