### ISSUE TITLE
Marketch crashes when text layers contain color + fill

### ISSUE THREAD

**Issue by pixi-stix** [tudou527/marketch#150]
**- Sketch version:** 46 (44423) and a few previous versions
**- Description:** When exporting, a toast displays that says 'exporting' but fails and doesn't export the zip file. This is caused by text layers that contain both a text color _and_ a fill color. 

**- Reproduction steps:** Create an empty artboard with a single text layer, add a fill, then run Marketch. **Deleting the fill layer will resolve the issue**.

**- Console output:**
```
Sketch	Exception: TypeError: layer.style().fill is not a function. (In 'layer.style().fill()', 'layer.style().fill' is undefined)
Sketch	Info: {
    column = 43;
    line = 403;
    sourceURL = "/Users/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Marketch/marketch.sketchplugin/Contents/Sketch/zip.cocoascript";
}
Sketch	TypeError: layer.style().fill is not a function. (In 'layer.style().fill()', 'layer.style().fill' is undefined)
line: 403
sourceURL: /Users/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Marketch/marketch.sketchplugin/Contents/Sketch/zip.cocoascript
column: 43
 
```

**Comment by MForever78** [comment]
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.
