### ISSUE TITLE
文字填充颜色之后无法导出zip

### ISSUE THREAD

**Issue by leonsco** [tudou527/marketch#152]
- Sketch version: 46.2
- Description: 文字填充颜色之后无法导出zip
- Screenshot: 
![_ 8vat bgloljxzaoj cgag](https://user-images.githubusercontent.com/18396127/29549441-e8a443e8-873a-11e7-8b35-e9a6da4678fe.png)

**Comment by MForever78** [comment]
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.
