### ISSUE TITLE
it can not work in Sketch 46.2

### ISSUE THREAD

**Issue by CrisJiao** [tudou527/marketch#155]
i find out the reason, it seems the issue is related to having Text Objects that have "Fills" in them. i delete all of them，then OK. i think it might be a bug. Hope you guys fix it.

**Comment by CrisJiao** [comment]
i find out the reason, it seems the issue is related to having Text Objects that have "Fills" in them. i delete all of them，then OK

**Comment by katestacio** [comment]
My text objects do not have fills and I still cannot get an exported file from marketch in my Sketch 46.2 version.

**Comment by banagale** [comment]
Also unable to export to zip successfully. The behavior is that it allows export location chooser, and appears to go through process of exporting, but no file is created.

**Comment by banagale** [comment]
If you are desperate to get this plugin working again, you can open the plugin package and make the changes shown [in this pull request](https://github.com/tudou527/marketch/pull/158).
