### ISSUE TITLE
Can't choose artboard to import after update to macOS High Sierra

### ISSUE THREAD

**Issue by aakaravaev** [tudou527/marketch#157]
![screen shot 2017-09-27 at 19 57 51](https://user-images.githubusercontent.com/32338464/30926650-7dd61c6c-a3be-11e7-9461-06f878b9f44a.jpg)
# Issue template

- Sketch version: 43.1
- Description: After update to macOS High Sierra 10.13 I can't to choose artboard to import. 
- Screenshot: ![screenshot](resource/1.jpg)

**Comment by aprilogao** [comment]
Sketch version: 46.2
Description: Export fail as zip after macOS updated to  High Sierra.

**Comment by aprilogao** [comment]
Sketch version: 46.2
Description: Export failure after macOS updated to High Sierra.

**Comment by tarjei** [comment]
@aprilogao have you tested this fork: 
https://github.com/MForever78/marketch

**Comment by aakaravaev** [comment]
> @aprilogao have you tested this fork:
> https://github.com/MForever78/marketch
Thanks!

**Comment by MForever78** [comment]
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.
