### ISSUE TITLE
it can not work in Sketch 47, please help out.

### ISSUE THREAD

**Issue by ghost** [tudou527/marketch#159]
# Issue template

To help you and us target the bug efficiently, we urge you to provide these essential information.

## Example

- Sketch version: 3.3.2(12043)
- Description: The value should be... but I see...
- Screenshot: ![screenshot](resource/1.jpg)

**Comment by rameshchindam** [comment]
Sketch version: 47
Description:  clicking on Export Zip file after some time spinning nothing happening.
Screenshot: screenshot

**Comment by jmaferreira** [comment]
I'm using Sketch 47.1. After exporting no file is created.
