### ISSUE TITLE
grid style issue

### ISSUE THREAD

**Issue by ashraf-ali-ca** [tudou527/marketch#16]
grid not displaying properly, I have selected the thumbnail image, but the grid is displayed at the top corner. 
![image](https://cloud.githubusercontent.com/assets/7900956/8757715/89fd77fa-2cd4-11e5-9176-51fe70ae14b9.png)

**Comment by tudou527** [comment]
This may be caused by the mask layer, i temporarily revert the code about this. please reinstall marketch and try.

**Comment by Neema** [comment]
i'm also still getting this issue with the current commit

**Comment by tudou527** [comment]
@Neema can you send me a copy of your sketch file for debug? tudou527#gmail.com
