### ISSUE TITLE
After exporting  no file is created when using sketch 47.1.

### ISSUE THREAD

**Issue by x5forever** [tudou527/marketch#162]
# Issue template

To help you and us target the bug efficiently, we urge you to provide these essential information.

## Example

- Sketch version: 3.3.2(12043)
- Description: The value should be... but I see...
- Screenshot: ![screenshot](resource/1.jpg)

**Comment by sashabeep** [comment]
I can confirm that on 42.1 zip file is also not created with latest version of marktech plugin

**Comment by eshapo** [comment]
Sketch version: 46.2
Description: I press "Confirm" button -> small message below "Exporting file..." telling me that something happening -> message disappears ->  "Symbol" page is opening -> nothing was exported anywhere

**Comment by MForever78** [comment]
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.

**Comment by dannyalright** [comment]
Heads up: Marketch is still at version `v1.0.22` in the `.sketchplugin` in master (and in Sketch Runner). So the same non-exporting issue is happening.

**Comment by MForever78** [comment]
Thanks @dannyalright for the heads up!

The version in the manifest is now updated as well.

**Comment by x5forever** [comment]
@MForever78 
Thanks!
I've tried it,the issue has been solved.

**Comment by dannyalright** [comment]
Yep. Works great, thank you
