### ISSUE TITLE
Not exporting

### ISSUE THREAD

**Issue by akspablo** [tudou527/marketch#165]
The plugin is not working when I try to export it. I already tried installing the previous versions of Sketch, as well uninstall and install again the marketch plugin, and still doesn't work. Do you have any news about? I tried in different projects to make sure and doesn't work.

- Sketch version: 47.1
- Marketch version: 1.0.22
- MacOS High Sierra 10.13.1

**Comment by thing360** [comment]
我也遇到同样的问题，求大神帮忙

**Comment by xixigeek** [comment]
have the same problem

**Comment by lewrryyhen** [comment]
same problem

**Comment by mauriciojuba** [comment]
Same problem

**Comment by MForever78** [comment]
Fixed in 6f4e2a6.

Please upgrade to 1.0.23.

**Comment by jbychg** [comment]
Upgraded to 1.0.23. Still not exporting. Using Sketch 48.2
