### ISSUE TITLE
exporting speed issue

### ISSUE THREAD

**Issue by ashraf-ali-ca** [tudou527/marketch#17]
compared to sketch-origami-export https://github.com/tarngerine/sketch-origami-export the plugin takes a while to export the files, I tested exporting a single artboard on sketch-origami I managed to export it in 7 seconds but with marketch it took a full minute. A way the plugin could reduce the time for export is to check if the same name also try using saveArtboardOrSlice to save the file.

````
var check_name_conflict  = function(layer, depth, artboard_name) {
  var was_conflict = false;
  if (array_contains(layer_names, artboard_name + [layer name])) {
      was_conflict = true;
      log_depth("Layer name conflict: <" + [layer name] + "> already exists in artboard <" + artboard_name + ">", depth);

      // Preserve layer name modifiers + - *
      var last_char = [layer name].slice(-1);
      var has_modifier = should_ignore_layer(layer) || should_flatten_layer(layer) || should_make_layer_own_image(layer);
      if (has_modifier) {
        [layer setName:[layer name].split(last_char)[0]]; // Remove last_char
      }
      [layer setName:[layer name] + " copy"];
      if (has_modifier) {
        [layer setName:[layer name] + last_char];
      }
      log_depth("Renaming to: <" + [layer name] + ">", depth);

      check_name_conflict(layer, depth, artboard_name);
    }

  return was_conflict;
}
````

**Comment by tudou527** [comment]
different from "sketch-origami" when you select "export every layer as image" marketch need more time to iterative layer 
![2015-07-20 19 21](https://cloud.githubusercontent.com/assets/1134658/8774729/cc194d30-2f13-11e5-9bc9-cf1285c903db.jpg)
