### ISSUE TITLE
Export won't work sketch 50.2 marketch 1.0.23

### ISSUE THREAD

**Issue by Royalbeck** [tudou527/marketch#175]
in any way I try to export from marketch it won't let me export artboards and pages. 
I have tried to duplicate the file 
different pages 
delete and reinstall the plugin 
close and relaunch sketch & plugin
restarted my mac
the app indicates "exporting" but doesn't create any marketch file. 

- Sketch version: 50.2
-marketch version: 1.0.23

**Comment by silvinacouto** [comment]
Same here.

**Comment by Royalbeck** [comment]
@silvinacouto look for another plugin "sketch measure" does what marketch does and more.

**Comment by silvinacouto** [comment]
@Royalbeck thanks, Sketch measure is also not working since I updated to version 52...

**Comment by aretore** [comment]
Same here... Neither Marketch, nor Sketch Measure are working :(

**Comment by Mihkach** [comment]
Are you going to fix this problem?

**Comment by Royalbeck** [comment]
@Mihkach looking as if no one is home. 
abandoned the project :/

**Comment by Mihkach** [comment]
@Royalbeck I'm sad. Used this tool for 2 years. It was great. But now I found another with same functions – https://github.com/utom/sketch-measure#spec-export. It works well.

**Comment by Royalbeck** [comment]
@Mihkach sketch measure is by far better

**Comment by MForever78** [comment]
We wrote and maintained marketch in volunteer and make it free to use. We all have our full time job to do.

Leaving comment like this won't help this project at all and it hurts the developers. It's open to community and we welcome pull requests if you can help fix problems.

That being said, I may find some time recently to fix this, hopefully.

**Comment by MForever78** [comment]
fixed in 49ebd0c9
