### ISSUE TITLE
sketch toolbox 闪退  ，这里可以留个下载的安装包吗？ 

### ISSUE THREAD

**Issue by longalong** [tudou527/marketch#177]
# Issue template

To help you and us target the bug efficiently, we urge you to provide these essential information.

## Example

- Sketch version: 3.3.2(12043)
- Description: The value should be... but I see...
- Screenshot: ![screenshot](resource/1.jpg)

**Comment by MForever78** [comment]
https://github.com/tudou527/marketch/releases
