### ISSUE TITLE
Export SVG not working for me

### ISSUE THREAD

**Issue by jmaferreira** [tudou527/marketch#179]
# Issue template

After export using marketch the SVG assets are not exported. Only the PNG version is available.
I've created multiple export settings, for PNG and SVG so I would expect both versions to be exported and available on the marketch preview page.

## Example

- Sketch version: 51.3(57544)
- Description: The exported assets don't include the SVG files
- Screenshots: 

![screen shot 2018-10-02 at 13 53 08](https://user-images.githubusercontent.com/3181302/46349732-c0d71200-c64a-11e8-8e1d-18b36545dcb4.png)
<img width="789" alt="screen shot 2018-10-02 at 13 49 10" src="https://user-images.githubusercontent.com/3181302/46349733-c0d71200-c64a-11e8-8c06-79caa57fd84b.png">

**Comment by MForever78** [comment]
Seem like a bug. Taking a look

**Comment by MForever78** [comment]
Turns out this is never a thing. To export svg please add a "svg" prefix to the layer's name.

**Comment by jmaferreira** [comment]
I've confirmed. It works. However, it would make much more sense to respect the formats defined on the "Export" tab, instead of having to change the names of existing layers.

**Comment by MForever78** [comment]
Yeah.. But that's not the original design. It requires some work to change.

I'll make it as an enhancement for next couple of versions but before that you can go with this workaround.

**Comment by jmaferreira** [comment]
Absolutely. Cheers.
