### ISSUE TITLE
Shape layer can't be selected if there is a text layer above

### ISSUE THREAD

**Issue by funtrip** [tudou527/marketch#182]
- Sketch version: 52.1(67048)
- Description: If there is a text layer above the shape layer, you can't select the shape layer below.
![image](https://user-images.githubusercontent.com/14296263/46859995-e8478f00-ce41-11e8-86f9-f9f130740fca.png)

**Comment by MForever78** [comment]
Looks like this is expected. Any basic Shape layer won't be exported anyway. And the layer group won't be exported either.

To be able to export this, try creating a combined shapeLayer using either Union / Subtract / Intersect / Difference:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/4675950/46911174-af262200-cf08-11e8-9e93-bf18ff6bb7b3.png">
