### ISSUE TITLE
Can't export zip file with Sketch 52.2

### ISSUE THREAD

**Issue by ekingm** [tudou527/marketch#183]
- Sketch version: 52.2
- Marketch version: 1.0.23

Description: Hi, I can't seem to export the zip file, It shows 'exporting' but nothing happens after that no file generated.  I saw this was also an issue back in 2017 issue #149, but with these versions of the application Sketch version - 45.2, Marketch version - 1.0.22

Please help, I love this plugin and is really very useful for our development team.

Thanks in advance!

<img width="537" alt="sketchversion" src="https://user-images.githubusercontent.com/3891848/46871612-e8269f80-cdff-11e8-815b-217f29e7195d.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/3891848/46871899-9e8a8480-ce00-11e8-8fb5-3caff8ad89d5.png">

**Comment by MForever78** [comment]
Can you try 1.0.24?

https://github.com/tudou527/marketch/releases
