### ISSUE TITLE
No hover info for shapes

### ISSUE THREAD

**Issue by ggolcher** [tudou527/marketch#187]
For Marketch under Sketch 52.3, I'm not getting hover information for shapes.

Text has all the necessary info, but any shapes just don't turn act on hover

**Comment by MForever78** [comment]
Thanks for reporting. I'm aware of this. Working on a fix recently. Since it's actually dup to #186 I'm closing this and tracking there

**Comment by ggolcher** [comment]
Thanks for letting me know. I wasn't aware of it because I don't speak Mandarin ;)
