### ISSUE TITLE
当Artboard的名字中存在"/"时，使用Spec Export导出功能时导出为空。

### ISSUE THREAD

**Issue by ninjaisun** [tudou527/marketch#34]
当Artboard的名字中存在"/"时，或者有一些非文字字符，然后使用Spec Export导出功能时，页面无法导出，或者导出为空。

**Comment by tudou527** [comment]
@ninjaisun  我试了一下在1.0.0这个版本上不会没有重现你遇到的问题。麻烦升级到1.0.0试试，如果还有问题的话，麻烦再联系我。

<img width="812" alt="2015-09-03 17 31 07" src="https://cloud.githubusercontent.com/assets/1134658/9655126/9cf400b0-5261-11e5-9336-e39f78eff5e2.png">
