### ISSUE TITLE
development process

### ISSUE THREAD

**Issue by ashraf-ali-ca** [tudou527/marketch#36]
Hi, I was wondering are you using XCode to create the plugin or just a using a normal text editor. I would like to contribute the project, I have seen a couple of bugs regarding the measurements be off by 1px.  Can you tell me the tools you use to write and debug the plugin?

I have tried to use sketch-devtools, but it does not work with the latest sketch version.

**Comment by tudou527** [comment]
@ashraf-ali-ca i use sublime text3.

**Comment by MForever78** [comment]
@ashraf-ali-ca 

First of all, any help will be appreciated!

We are not using XCode to develop this plugin, for now at least. You can use any of your favorite editors.

The project can be divided into two major parts. First of which is CocoaScript part. We use `Util.log` or `console.log` as an alias to pop up a console and log things. Second is basically front end stuff. You are using the data generated by your cocoa script and display everything on a web page. So you will need common front end debug approach.

If you still have questions, please let me know.

Maybe I'll write a contribution guide later on.

**Comment by tudou527** [comment]
@MForever78 感谢补充😄   现在的学校真好，10点了+也不断电

**Comment by MForever78** [comment]
@tudou527 :joy: 哪有那么惨，我们可是 24 小时供电和 IPv6 无墙环境的 :stuck_out_tongue_closed_eyes:
