### ISSUE TITLE
split the json data

### ISSUE THREAD

**Issue by ashraf-ali-ca** [tudou527/marketch#39]
it would be nice to have the option to split the JSON data by each artboard when exporting all artboards so that we are only loading required data. I would imagine with phasing all the artboard in one single JSON file is not good for loading time.

**Comment by MForever78** [comment]
@ashraf-ali-ca 

The main speed concern we see now is the export process, cuz it will travel all artboards and all layers, which is slow. So currently we are providing the option to let you export only one artboard.

We think the JSON load time in all modern browsers is so fast that can be ignored in most circumstances. We are exporting all data to one JSON file just out of convenience. But if you can prove that the JSON load time is notably slow, we certainly can do a split.

Thanks.

**Comment by MForever78** [comment]
@tudou527 

我觉得 JSON 加载时间根本可以忽略不计吧...

**Comment by tudou527** [comment]
@MForever78 试了一下IOS9的sketch稿，3个页面7个画板，150K+，就算上传到服务器上加载时间可以忽略。1M左右再考虑拆分比较合适。
