### ISSUE TITLE
support line breaks

### ISSUE THREAD

**Issue by ashraf-ali-ca** [tudou527/marketch#41]

**Comment by tudou527** [comment]
@ashraf-ali-ca can you describe it in detail？

**Comment by ashraf-ali-ca** [comment]
@tudou527 if you have a line break in the sketch file , it fails to load the js file due to line breaks are not properly encoded when generating the js file. try using this file to generate the assets data. 
[Muse.sketch | uploaded via ZenHub](https://files.zenhub.io/55ff09c7e93156d42f4c4abb)
