### ISSUE TITLE
你好，单个画板生成的html包体积太大

### ISSUE THREAD

**Issue by dsncat** [tudou527/marketch#44]
我看了一下原来包含所有@1x @2x切图

**Comment by tudou527** [comment]
@dsncat  导出的时候不选择“把每个图层作为图片导出” 会小很多。不知道这样能不能满足你的需求。

![snip20150926_13](https://cloud.githubusercontent.com/assets/1134658/10118228/453ea8f0-64a6-11e5-9ef2-0b83dcf1add9.png)
