### ISSUE TITLE
Code box is impossible to see

### ISSUE THREAD

**Issue by 2gen** [tudou527/marketch#47]
The code box in the sidebar is broken in Firefox.
![demo firefox today at 1 58 14 pm](https://cloud.githubusercontent.com/assets/2212403/10143994/307bec9a-65e9-11e5-8052-8bf362f6fe7b.png)

**Comment by MForever78** [comment]
应该是这里的 `textarea` 的 CSS 里的 `white-space: nowrap` 生效了。看起来好像 Chrome，Safari 和 Firefox 中只有 FF 的行为是符合规范的，应该把这句去掉就好了？没有看懂这里加这一句的意义。

**Comment by tudou527** [comment]
@MForever78 是希望每行css的定义不换行。看起来是换行符引起的。晚上回去看看。
