### ISSUE TITLE
[Feature Request] Display Font Sizes for Android and iOS 

### ISSUE THREAD

**Issue by pranjaltech** [tudou527/marketch#48]
<img width="204" alt="screen shot 2015-10-06 at 1 00 49 pm" src="https://cloud.githubusercontent.com/assets/71014/10302470/4f8f18d6-6c2a-11e5-87c4-b9fa47f31a81.png">

Upon selecting text, we should have font sizes in *points* and *scalable pixels*, that will be very useful for Android and iOS App Design. 

By the way, great job with the plugin! This is one of the best plugins for Sketch.

**Comment by MForever78** [comment]
Done in #49 , waiting to be reviewed. Thanks for your feedback!

**Comment by pranjaltech** [comment]
Awesome!
