### ISSUE TITLE
依旧无法导出

### ISSUE THREAD

**Issue by lvhailong** [tudou527/marketch#5]
提示导出成功，但是在目的路径下还是找不到导出的文件。

**Comment by noyobo** [comment]
+1  iMac  sketch 3.2.2

**Comment by noyobo** [comment]
update: 卸载后, 重装,问题解决

**Comment by tudou527** [comment]
@lvhailong 请问你的sketch是从appstore上下载还是从官网下载安装的？目前发现从appstore上下载的sketch因为沙箱限制导致无法导出。

**Comment by noyobo** [comment]
@tudou527 我的是从 app store 下载的 .

**Comment by tudou527** [comment]
@noyobo，你的osx版本号是多少？

**Comment by noyobo** [comment]
@tudou527  10.10.4

**Comment by jaylong** [comment]
和@noyobo 一样 重装后问题解决。
