### ISSUE TITLE
Not working in Beta 3.4

### ISSUE THREAD

**Issue by bworley29** [tudou527/marketch#53]
I'm not able to get the plugin to work using any of the available Export options.  This was tried on different files and Artboards.

**Comment by tudou527** [comment]
@bworley29 it seems to work fine on my computer
![12](https://cloud.githubusercontent.com/assets/1134658/10715852/f1e62fe0-7b5f-11e5-9943-8c1927225f52.jpg)
can you show me more info? for example: screenshot

**Comment by bensmeets** [comment]
Not working in final 3.4 either. No error, just after the prompt in your screenshot, it does nothing and goes back to Sketch.

**Comment by bensmeets** [comment]
It only seems to work if you exactly 1 artboard selected, and choose "selected artboards only"

**Comment by tudou527** [comment]
please confim you marketch version is 1.0.5.
I recorded my screen  as a demo:  https://www.youtube.com/watch?v=07auvdkIZTw&feature=youtu.be

**Comment by bensmeets** [comment]
Both versions are correct. Still nothing generated (no zip file anywhere). It did change a bit in regards to the last time though. Where before, I would select to export and it almost instantly went back to Sketch without having done anything, it now shows the beachball first a couple of seconds. But after it is gone, there is still nothing (no error either btw).

**Comment by tudou527** [comment]
@bensmeets  can you open `console.app` and search `sketch` keyword then send my the log info?  tudou527#gmail.com

**Comment by bensmeets** [comment]
Sure, I think it's in here somewhere.

```
30-10-15 14:43:24,115 Sketch[83826]: Exception: *** -[NSConcreteTextStorage attribute:atIndex:effectiveRange:]: Range or index out of bounds
30-10-15 14:43:24,115 Export as zipFile (Sketch Plugin)[83826]: *** -[NSConcreteTextStorage attribute:atIndex:effectiveRange:]: Range or index out of bounds
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const: conn 0x2671b legacy 2
30-10-15 14:43:25,391 Sketch[83826]: Backtrace (at 201576):
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x00007fff9a792dc8 CGSDisableUpdate + 142
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  1   AppKit                              0x00007fff88a4cdb2 NSDisableScreenUpdates + 80
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  2   Sketch                              0x000000010422c26a Sketch + 275050
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  3   Sketch                              0x0000000104209db6 Sketch + 134582
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  4   Sketch                              0x000000010423c103 Sketch + 340227
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  5   Sketch                              0x00000001042f7701 Sketch + 1107713
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  6   Sketch                              0x000000010423bef6 Sketch + 339702
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  7   Sketch                              0x0000000104491fbb Sketch + 2789307
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  8   Sketch                              0x000000010449206f Sketch + 2789487
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  9   Sketch                              0x000000010423dfa2 Sketch + 348066
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  10  libffi.dylib                        0x00007fff8ecdcf14 ffi_call_unix64 + 76
30-10-15 14:43:25,391 Sketch[83826]: void CGSUpdateManager::log() const:  11  ???                                 0x00007fe30557dca0 0x0 + 140613023947936
```

**Comment by tudou527** [comment]
@bensmeets  what's your osx version?

**Comment by bensmeets** [comment]
el capitan

**Comment by MForever78** [comment]
@tudou527 最近有点忙，才看到这个 issue

出现 `NSConcreteTextStorage attribute:atIndex:effectiveRange:]: Range or index out of bounds` 这个错误应该是使用了字符串相关操作引起的，我看了一下很有可能是这里出问题了：

https://github.com/tudou527/marketch/blob/master/marketch.sketchplugin%2FContents%2FSketch%2Fzip.cocoascript#L115

现在不能十分确定，给你参考一下

**Comment by tudou527** [comment]
@MForever78  好，我调试看看
