### ISSUE TITLE
Measurement issues

### ISSUE THREAD

**Issue by czavani** [tudou527/marketch#56]
Hey there, 

Our team designs @2x, and we would like to have an option that would allow our developers to read the doc as follows:
-a @1x option should be 0.5px
-a @3x option should be 1.5px
Anything of that sort in the works? 
Thanks!

**Comment by tudou527** [comment]
@czavani  sorry i can't understand

**Comment by MForever78** [comment]
@tudou527 

我们现在的做法是把 @1x 的长宽值按照原尺寸输出，@2x @3x 依次按比例缩小成原来的 1/2， 1/3。

她的意思是说，她们直接设计出的图就是 @2x 的，她们想要 @2x 的再按原尺寸输出。@1x @2x 分别显示成原尺寸的 1/2，2/3 这样。

**Comment by brianmoyano** [comment]
I think the plugin thinks every document it's designed at @1x. So you should work like that.
PS: Why do you work at 2x if it's better work at 1x?
