### ISSUE TITLE
Export SVG assets instead of PNG?

### ISSUE THREAD

**Issue by bradhodson** [tudou527/marketch#57]
Wondering if you will be providing the option of exporting to SVG instead of PNG for the accompanying assets? Also, we would need a 3x export as well for all assets.

**Comment by tudou527** [comment]
i will add an options about export image type and size in next verson.

**Comment by bradhodson** [comment]
Awesome! Can't wait. This tool is LEGIT!

**Comment by bradhodson** [comment]
Thank you so much!!!

**Comment by bradhodson** [comment]
Thank you!
http://www.jobnimbus.com/

Brad Hodson

 

mail | 
mailto:brad@jobnimbus.com
phone | (855) 964-6287 x705

On Thu, Jan 14, 2016 at 8:28 AM tudou527

<
mailto:tudou527 <notifications@github.com>
> wrote:

Closed
https://github.com/tudou527/marketch/issues/57
via
https://github.com/tudou527/marketch/commit/fbbd53023c9a09e3deac8f2d27c57135deb8b012
.

—

Reply to this email directly or
https://github.com/tudou527/marketch/issues/57#event-515165536
.

https://github.com/tudou527/marketch/issues/57#event-515165536
