### ISSUE TITLE
Stopped working today after new update of Sketch (3.4.4)

### ISSUE THREAD

**Issue by Acsidian** [tudou527/marketch#59]
Marketch plugin simply does not return anything.

Sketch Version 3.4.4 (17249)

**Comment by smpldsgn** [comment]
I noticed this too, 'Export as zipFile' seems to be broken and does not produce anything
on Sketch Version 3.4.4 (17249)

**Comment by tungjacob** [comment]
Yes, I've got the same problem with Sketch version 3.4.4

Cannot product anything with "Export as Zip file"

Best regards,
TungNT

**Comment by amiltonpaglia** [comment]
Same problem here :/

**Comment by bentographics** [comment]
Same problem here, Marketch does not export anything. On Sketch v3.9.1 now.

Any change this will be fixed soon?
