### ISSUE TITLE
导出不了Zip

### ISSUE THREAD

**Issue by ozygod** [tudou527/marketch#65]
系统日志里提示如下：
TypeError: MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_ is not a function. (In 'MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_( layer  ,sliceRect  ,false)', 'MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_' is undefined)

**Comment by tudou527** [comment]
你使用的是哪个版本？

**Comment by ozygod** [comment]
当时是3.4.1，不过我更新到最新版本就可以导出了。
