### ISSUE TITLE
Why GoogleAnalyticsObject?

### ISSUE THREAD

**Issue by MikaDo0211** [tudou527/marketch#66]
I saw this code in file export

< script >
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-67070169-1', 'auto');ga('send', 'pageview');
< /script >

I don't understand. Why insert script in file export ???

**Comment by tudou527** [comment]
In order to let me know whether it is worth to maintain this project.

**Comment by tungjacob** [comment]
This plugin is by far the most useful and practical plugin that makes a
bridge between Designers and Developers, and no doubt worth maintaining and
upgrading for the Sketch community. Thanks for your time.

Best regards,
TungNT
