### ISSUE TITLE
No export with slices on artboard

### ISSUE THREAD

**Issue by giuseppebergman** [tudou527/marketch#67]
Export zip files does not complete (no file generated) if one of the selected artboards contains slices.
I moved the slice layers outside my artboard "folder" (without moving them inside the viewport), and it worked back.

Here's the error log:

    12/01/2016 14:40:19,883 Sketch[1415]: Info: {
        column = 41;
        line = 342;
        sourceURL = "/Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/marketch-master/marketch.sketchplugin/Contents/Sketch/zip.cocoascript";
    }

    12/01/2016 14:40:19,883 Export as zipFile (Sketch Plugin)[1415]: TypeError: undefined is not a function (evaluating 'layer.style()')
    line: 342
    sourceURL: /Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/marketch-master/marketch.sketchplugin/Contents/Sketch/zip.cocoascript
    column: 41

Great plugin otherwise. Thank you for you work!

**Comment by fatihturan** [comment]
It does not work for me with last update. But I have a solution for reverting previous working Marketch version:

1. Remove the Marktech plugin folder from ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ or from Sketch Toolbox
2. Go to same folder (~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/) and clone the repo of Marketch with `git clone https://github.com/tudou527/marketch.git` command on Terminal.
3. When you in the plugin folder (~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/marketch) checkout on older commit with `git checkout 39eb1055b1ee3b10f53c4edf3305dfd11344eb63`

**Comment by giuseppebergman** [comment]
Fatih, are you talking about the slices related issue?

**Comment by fatihturan** [comment]
Ah, I assumed you have experiencing same issue with me. Sorry about it. :)

Latest Marketch plugin did not work for me and reverted to old commit. So I though it would helpful for you but it doesn't related to your issue. Forget it.

**Comment by giuseppebergman** [comment]
Tudou527, thanks for the quick reaction, but I don't get what changed in commit https://github.com/tudou527/marketch/commit/7293058473611a3fd6d5e9031ce424d947e0fb0b: deleted a bracket and added the same? 
Anyway, https://github.com/tudou527/marketch/commit/7293058473611a3fd6d5e9031ce424d947e0fb0b doesn't change anything to the "slice preventing export" problem.

**Comment by tudou527** [comment]
orrect commit is https://github.com/tudou527/marketch/commit/b552518b967b719a3fce4717c755bbd583c7113b 

othes is for testing close issues by commit :)

**Comment by giuseppebergman** [comment]
Ok, the slice issue is fixed indeed with https://github.com/tudou527/marketch/commit/b552518b967b719a3fce4717c755bbd583c7113b . Thanks a lot!

**Comment by gajenrp** [comment]
Hi,

Marketch plugin is not working for sketch 41 version...please give me solution..
