### ISSUE TITLE
About export

### ISSUE THREAD

**Issue by ninjaisun** [tudou527/marketch#69]
你好，
想问下，导出的时候能不能有个选项，比如“不包括源文件在zip中”，因为很多时候我导出的时候不想把源文件包含进去。所以现在我每次导出后先删除里面的源文件，再zip一下，非常麻烦。希望下个版本中能加入这个功能：）
![image](https://cloud.githubusercontent.com/assets/436731/12378355/d3b23cb4-bd75-11e5-842b-988a0392f421.png)

**Comment by tudou527** [comment]
不应该是这样的吗？请升级到1.0.11

![image](https://cloud.githubusercontent.com/assets/1134658/12419222/a3dc4cca-beef-11e5-9430-b352e020e6d8.png)

**Comment by ninjaisun** [comment]
Tried it, it works, thanks very much.
