### ISSUE TITLE
can not export

### ISSUE THREAD

**Issue by ArvX** [tudou527/marketch#70]
第一次下载是1.0.7 用的sketch版本为3.4.4，然后升到1.0.9 1.0.11都不能导出 试过有切片的和没有切片的 都不能导出。

然后这是用sketch自带的web template导出时生成的log

1/18/16 1:21:59.932 PM	Sketch[3052]	Exception: TypeError: MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_ is not a function. (In 'MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_( layer  ,sliceRect  ,false)', 'MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_' is undefined)
1/18/16 1:21:59.932 PM	Sketch[3052]	Info: {
    column = 76;
    line = 925;
    sourceURL = "/Users/steve/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Marketch/marketch.sketchplugin/Contents/Sketch/zip.cocoascript";
}
1/18/16 1:21:59.933 PM	Export as zipFile (Sketch Plugin)[3052]	TypeError: MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_ is not a function. (In 'MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_( layer  ,sliceRect  ,false)', 'MSSliceMaker.slicesFromExportableLayer_inRect_useIDForName_' is undefined)
line: 925
sourceURL: /Users/steve/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Marketch/marketch.sketchplugin/Contents/Sketch/zip.cocoascript
column: 76

**Comment by tudou527** [comment]
你的系统是哪个版本？sketch是从appstore还是sketch官方下载的。

**Comment by ArvX** [comment]
系统10.11.2 sketch是第三方下下来的

**Comment by MForever78** [comment]
@ArvX 

第三方？只有 Sketch [官方的版本](https://www.sketchapp.com/) 是被支持的，App Store 中和其他地方提供的版本应该都无法正常运行。

从 log 来看奇怪的地方是 Sketch 提供的一些标准函数被阉割了，我猜可能是所谓的第三方做的吧。

**Comment by ArvX** [comment]
OK @MForever78 我去试试官方版本是否能运行

**Comment by ArvX** [comment]
试了一下发现的确官方版本能正常使用 看来是sketch的问题…
