### ISSUE TITLE
Not working on version 3.5

### ISSUE THREAD

**Issue by mattusk** [tudou527/marketch#72]

**Comment by zilos** [comment]
can we please make this work on this version of Sketch? Thank you so much for the hard work.

**Comment by fatihok** [comment]
I have also the same issue. Thank you so much, your plugin is saving my life. :)

**Comment by bxia** [comment]
For me it works on 3.5 but the options to **export selected artboards** and **export artboards on current page** don't work; it always exports all artboards.
Thanks for working on this!
