### ISSUE TITLE
marketch doesn't generate zip file (

### ISSUE THREAD

**Issue by marrru** [tudou527/marketch#77]
Hi! marketch doesn't generate zip file.
When I try to use marketch everything works how it have to & I see message that file is generating, but there is nothing in chosen folder. I've tried different options and files, but there is the same result
Marketch version 1.0.13
Sketch version  3.4.2
Maybe you can help me or say what else I should try to do

**Comment by giuseppebergman** [comment]
Plugin 1.0.13 is known to work with Sketch v3.5.1 (and it does here), so I would update Sketch if I were you. I'm not the dev, though.

**Comment by marrru** [comment]
thanks, I'll try

**Comment by WhatsNewSaes** [comment]
I can confirm that after updating, the plugin works. 

This is the best plugin for sketch. Thank you!

**Comment by giuseppebergman** [comment]
Ok, this issue can be closed, then.
