### ISSUE TITLE
Sketch 3.7 symbols have no interaction

### ISSUE THREAD

**Issue by ChadNicholas** [tudou527/marketch#89]
- Create an artboard
- Add some shapes
- Add some symbols
- Export artboard
- View exported index page

At this point, I can inspect any of the shapes and get the distance to other shapes, but the symbols do not respond to mouse hover or click events. 

I tried exporting the new Symbols page artboards only, but Marketch seems to just fail silently. Exporting All Artboards does the same, which means that there isn't an easy work around to get style info from a Symbol.

**Comment by yoavchen** [comment]
+1

**Comment by piernerb** [comment]
+1

**Comment by cr3won3** [comment]
+1

**Comment by RayPS** [comment]
Before Marketch fix the compatibility. You can try the alternative plugin `Sketch Measure` instead:
https://github.com/utom/sketch-measure
![](https://camo.githubusercontent.com/a54faa8546f27b8365acaa5b3f4f6b2385507c55/687474703a2f2f75746f6d2e64657369676e2f6d6561737572652f332e7069635f68642e6a7067)

**Comment by jingfeng0510** [comment]
Just made a copy of the sketch file, opened it and deleted the symbols page > ZIP Export will work .
