### ISSUE TITLE
Zip file is not created

### ISSUE THREAD

**Issue by Gregmcor** [tudou527/marketch#90]
Sketch 3.7.1
- Create a new file
- add any element
- Export as Zip via Marketch
- Zip file does not appear in any folder.

**Comment by FoundDegree** [comment]
+1 ... No ZIP File generated! HELP!!

**Comment by botezalexandru** [comment]
Same problem here. Don't know what to do.

**Comment by jingfeng0510** [comment]
Deleting the symbol page can temporarily solve the problem.

**Comment by RayPS** [comment]
Before Marketch fix the compatibility. You can try the alternative plugin `Sketch Measure` instead:
https://github.com/utom/sketch-measure
![](https://camo.githubusercontent.com/a54faa8546f27b8365acaa5b3f4f6b2385507c55/687474703a2f2f75746f6d2e64657369676e2f6d6561737572652f332e7069635f68642e6a7067)

**Comment by FoundDegree** [comment]
@jingfeng0510 Thx ... you saved my ass! Just made a copy of my sketch file, opened it and deleted the symbols page > ZIP Export is working! Fingers crossed that it will be fixed soon!

**Comment by botezalexandru** [comment]
@jingfeng0510 Thanks
Your solution worked.

**Comment by tudou527** [comment]
fixed in [1.0.19 ](https://github.com/tudou527/marketch/commit/a1563844f493edff4abe6dc2e7e6d3fc98c9986a#diff-2a191df9850c714cbd7231191ffa83ccR116)

**Comment by FoundDegree** [comment]
Thx a lot @tudou527!!
