### ISSUE TITLE
Symbols still don't work in 1.0.19

### ISSUE THREAD

**Issue by yoavchen** [tudou527/marketch#92]
Updated to 1.0.19, but i don't see any change from 1.0.18 in regards with the new symbols of Sketch 3.7.

**Comment by tudou527** [comment]
sorry 1.0.19 is a bugfixed version. new feature with symbols will available in 1.0.20  a few days later.

**Comment by chenglpc** [comment]
1.0.19在sketch3.7.1输出后上面看不到画板。土豆你们加油啊，我爱你们！

**Comment by tudou527** [comment]
how about 1.0.20 ？

**Comment by yoavchen** [comment]
Sketch Toolbox downloaded 1.0.20 somehow (even though its not shown on GitHub) and symbols still don't work there.

**Comment by tudou527** [comment]
@yoavchen  can you send me a example sketch file, symbols work fine on my compture.

**Comment by yoavchen** [comment]
Hi,

it seem the problem is with nested symbols.
i attached a sample file.

please check and see if this works for you.

thanks

YC

**Comment by yoavchen** [comment]
I thought its because i used nested symbols, but It looks like i can't
export specific artboards without the symbols page.
i have several pages with many artboards and i need specific control over
my exports.

**Comment by tudou527** [comment]
if you select 'Send Symbol to "Symbols" Page'  you can add a `-` prefix to prevent symbol page export. but the symbols layer still will be exported

![image](https://cloud.githubusercontent.com/assets/1134658/15077546/9117bce0-13e1-11e6-8f77-2c5c78d610ff.png)

![image](https://cloud.githubusercontent.com/assets/1134658/15077434/fdd8d158-13e0-11e6-9c45-640798d4dd6f.png)

**Comment by yoavchen** [comment]
Sorry tudou527, but i don't understand how does it help.
The symbols are not selectable regardless of their name in any of my files.
can you send me a sample sketch file where export it does work?

**Comment by tudou527** [comment]
please try 1.0.21

**Comment by yoavchen** [comment]
HI,

i'm sorry but 1.0.21 still have issues.
i'm still getting every symbol exported separately as well, even if i
requested to export the selected Artboards only.

i saw that "Sketch Measure Plus" plugin was made with your collaboration
and its working very well, without exporting every symbol.
the only reason i don't use it is because it doesn't provide the css for
the elements.

Please try to remove the individual symbols from the export.
thanks,

YC
