### ISSUE TITLE
Suppress Symbols from being viewable in export

### ISSUE THREAD

**Issue by golauree** [tudou527/marketch#95]
Can you please have an option to suppress the Symbols navigation from showing in the left hand nav generated by the export?   Having this show up will just confuse the developers I give these specs to.   Thanks!

**Comment by tudou527** [comment]
you can add a  '-' to prevent symbol export 

![image](https://cloud.githubusercontent.com/assets/1134658/14856142/7f4ec374-0cc9-11e6-99b6-d67026bc2b46.png)

![image](https://cloud.githubusercontent.com/assets/1134658/14856205/bd7e7568-0cc9-11e6-93b7-217afad2f796.png)
