### ISSUE TITLE
Content disappears

### ISSUE THREAD

**Issue by anujaya** [tudou527/marketch#96]
Sketch version: 3.7.2 (28276)

Description: When I use Marketch on some of my Sketch files, it exports successfully, but when I unzip the file and open the HTML file, the tabs for each art board are shown, but none of the content shows. But when I copy those artboards to a new Sketch file and repeat the process it works perfectly. 

Screenshots:
Content doesn't show up
<img width="1440" alt="screen shot 2016-04-26 at 3 38 54 pm" src="https://cloud.githubusercontent.com/assets/3332899/14831778/201985d8-0bc5-11e6-9a2c-d59567f88ff8.png">

It exports successfully with all the files there
<img width="929" alt="screen shot 2016-04-26 at 3 43 07 pm" src="https://cloud.githubusercontent.com/assets/3332899/14831909/a302419c-0bc5-11e6-9e41-a93e3e8e325b.png">

**Comment by chenglpc** [comment]
The same problem,We are in a really big hurry...

**Comment by tudou527** [comment]
@anujaya can you [send me](mailto:tudou527@gmail.com) you sketch for test?

**Comment by chenglpc** [comment]
@tudou527 我可以帮测么。。

**Comment by barmallion** [comment]
Problem in nested symbols. If i delete all symbols on "Symbols" page - all works perfectly.

**Comment by tudou527** [comment]
please upgrade to 1.0.20 then try export. thansk

**Comment by barmallion** [comment]
Thank you very much!
